#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_49972_cmather")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertndhCareer(ndhCareer instance);
  partial void UpdatendhCareer(ndhCareer instance);
  partial void DeletendhCareer(ndhCareer instance);
  partial void InsertndhWaitTime(ndhWaitTime instance);
  partial void UpdatendhWaitTime(ndhWaitTime instance);
  partial void DeletendhWaitTime(ndhWaitTime instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_49972_cmatherConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ndhCareer> ndhCareers
	{
		get
		{
			return this.GetTable<ndhCareer>();
		}
	}
	
	public System.Data.Linq.Table<ndhWaitTime> ndhWaitTimes
	{
		get
		{
			return this.GetTable<ndhWaitTime>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndhCareers")]
public partial class ndhCareer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _title;
	
	private string _location;
	
	private System.Nullable<System.DateTime> _date;
	
	private string _department;
	
	private string _shift;
	
	private string _hours;
	
	private string _description;
	
	private string _wage;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnshiftChanging(string value);
    partial void OnshiftChanged();
    partial void OnhoursChanging(string value);
    partial void OnhoursChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnwageChanging(string value);
    partial void OnwageChanged();
    #endregion
	
	public ndhCareer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50)")]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="VarChar(50)")]
	public string shift
	{
		get
		{
			return this._shift;
		}
		set
		{
			if ((this._shift != value))
			{
				this.OnshiftChanging(value);
				this.SendPropertyChanging();
				this._shift = value;
				this.SendPropertyChanged("shift");
				this.OnshiftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hours", DbType="VarChar(50)")]
	public string hours
	{
		get
		{
			return this._hours;
		}
		set
		{
			if ((this._hours != value))
			{
				this.OnhoursChanging(value);
				this.SendPropertyChanging();
				this._hours = value;
				this.SendPropertyChanged("hours");
				this.OnhoursChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wage", DbType="VarChar(50)")]
	public string wage
	{
		get
		{
			return this._wage;
		}
		set
		{
			if ((this._wage != value))
			{
				this.OnwageChanging(value);
				this.SendPropertyChanging();
				this._wage = value;
				this.SendPropertyChanged("wage");
				this.OnwageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndhWaitTime")]
public partial class ndhWaitTime : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _referenceID;
	
	private System.Nullable<int> _staff;
	
	private System.Nullable<System.TimeSpan> _waitTime;
	
	private System.Nullable<System.DateTime> _updated;
	
	private string _notes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnreferenceIDChanging(int value);
    partial void OnreferenceIDChanged();
    partial void OnstaffChanging(System.Nullable<int> value);
    partial void OnstaffChanged();
    partial void OnwaitTimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnwaitTimeChanged();
    partial void OnupdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
	
	public ndhWaitTime()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int referenceID
	{
		get
		{
			return this._referenceID;
		}
		set
		{
			if ((this._referenceID != value))
			{
				this.OnreferenceIDChanging(value);
				this.SendPropertyChanging();
				this._referenceID = value;
				this.SendPropertyChanged("referenceID");
				this.OnreferenceIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff", DbType="Int")]
	public System.Nullable<int> staff
	{
		get
		{
			return this._staff;
		}
		set
		{
			if ((this._staff != value))
			{
				this.OnstaffChanging(value);
				this.SendPropertyChanging();
				this._staff = value;
				this.SendPropertyChanged("staff");
				this.OnstaffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waitTime", DbType="Time")]
	public System.Nullable<System.TimeSpan> waitTime
	{
		get
		{
			return this._waitTime;
		}
		set
		{
			if ((this._waitTime != value))
			{
				this.OnwaitTimeChanging(value);
				this.SendPropertyChanging();
				this._waitTime = value;
				this.SendPropertyChanged("waitTime");
				this.OnwaitTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated", DbType="DateTime")]
	public System.Nullable<System.DateTime> updated
	{
		get
		{
			return this._updated;
		}
		set
		{
			if ((this._updated != value))
			{
				this.OnupdatedChanging(value);
				this.SendPropertyChanging();
				this._updated = value;
				this.SendPropertyChanged("updated");
				this.OnupdatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="VarChar(50)")]
	public string notes
	{
		get
		{
			return this._notes;
		}
		set
		{
			if ((this._notes != value))
			{
				this.OnnotesChanging(value);
				this.SendPropertyChanging();
				this._notes = value;
				this.SendPropertyChanged("notes");
				this.OnnotesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
